# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0013_auto_20161120_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='头像',
            new_name='avatar',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='姓名',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='性别',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('U', 'Other')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='choice',
            field=models.CharField(choices=[('dislike', 'dislike'), ('like', 'like'), ('normal', 'normal')], max_length=10),
        ),
    ]
